export const DATE_PAYLOAD_FORMAT = 'YYYY-MM-DD HH:mm:ss A'
export const SYSTEM_DATE_FORMAT = 'L LT'
export const DATE_VIEW_IMAGE_PAYLOAD_FORMAT = 'YYYYMMDD'
export const DATE_TIME_VIEW_IMAGE_PAYLOAD_FORMAT = 'YYYYMMDDHHmmss'
